import { ReactNode } from 'react'
import { Roboto } from 'next/font/google'

import './globals.css'
import { HandleCollectionsContextProvider } from '@/context/handleCollectionsContext'

const roboto = Roboto({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <HandleCollectionsContextProvider>
          {children}
        </HandleCollectionsContextProvider>
      </body>
    </html>
  )
}
